version: '3.6'
services:
  database:
    image: mariadb
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=angular-app
  adminer:
    image: adminer
    ports:
      - '8082:8080'
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade